variables:
  # For full list of project level variables see https://docs.dataops.live/docs/concepts/project-settings/

  #################################################################################################################
  ## YOU SHOULD CHANGE THESE BEFORE RUNNING YOUR FIRST PIPELINE                                                  ##
  #################################################################################################################

  ## This defines the prefix used for all Snowflake Databases and other objects using namespacing of prefix or both
  ## Set this to something meaningful for you. By default this will use a version of your project path and name
  ## https://docs.dataops.live/docs/sole/user-guide/namespace-environment-management#namespace-management/
  DATAOPS_PREFIX: DATAOPS_EVENT

  ## DataOps Vault and secrets
  ## See https://docs.dataops.live/docs/concepts/vault/
  ## You should set this to something long and unique to you
  DATAOPS_VAULT_KEY: $CI_COMMIT_SHA

  ## Use "main" as the production branch
  DATAOPS_BRANCH_NAME_PROD: main

  ## Use the DEV environment for all feature branch resources
  ## (apart from the main $DATAOPS_DATABASE, which will still be created individually for each feature branch)
  DATAOPS_FEATURE_BRANCH_NONDB_ENV_NAME: DEV

  ## Make persistent cache relative to the snowflake account
  DATAOPS_PERSISTENT_CACHE_DIR: /agent_cache/$DATAOPS_SNOWFLAKE_ACCOUNT

  AGENT_TAG: ez-ec2-runner-dataopslive-events-prod

  ## Also before you run your first pipeline, please set the correct value in the agent_tag.yml

  #################################################################################################################
  ## YOU CAN CHANGE THESE                                                                                        ##
  #################################################################################################################

  ## Secrets Manager Configurations
  ## See https://docs.dataops.live/docs/orchestration/secretsmanager-orchestrator/

  # NEW for DataOps.live Events
  SECRETS_MANAGER: "none"
  # SECRETS_AWS_REGION: eu-west-2

  ## Use this if using Secrets Manager via attached IAM Role
  # SECRETS_AWS_USE_ROLE: 1

  ## Use this to select a subset of secrets by path
  # SECRETS_SELECTION: XXXXX

  ## Use this if using Secrets Manager via Access Key and Secret
  # SECRETS_AWS_ACCESS_KEY_LOCATION: AWS.DEFAULT.ACCESS_KEY
  # SECRETS_AWS_SECRET_KEY_LOCATION: AWS.DEFAULT.SECRET_KEY

  ## This tells the DataOps project to ignore Snowflake Variables set as part of the Group or Project configuration
  ## that would have been set if your tenant was originally setup via Snowflake Partner Connect.
  ## You should move to using a local vault file or Secrets Manager for credential management.
  # SKIP_SNOWFLAKE_VARS: 1

  ## This tells the testing engines to treat an error (i.e. the test can't be run for some reason) as a failure
  ## https://docs.dataops.live/docs/orchestration/transform-orchestrator/
  TREAT_TEST_ERRORS_AS_FAILED: 1

  ## This tells DataOps to render the contents of DATAOPS_VAULT_CONTENT into the vault.
  ## This is very useful if you have your secrets in a secrets manager without the ability to
  ## store them in the structure that DataOps needs. You can use this vault.yml (actually the template version of this)
  ## to map variables that have come from secrets manager into the vault structure that other DataOps jobs expect.
  DATAOPS_VAULT_CONTENT: $CI_PROJECT_DIR/vault-content/vault.yml

  #################################################################################################################
  ## YOU SHOULD GENERALLY NOT ENABLE THESE IN CONFIG - THEY ARE DESIGNED TO BE USED AS AD-HOC PIPELINE VARIABLES ##
  #################################################################################################################

  # NEW for DataOps.live Events
  DATAOPS_SNOWFLAKE_ACCOUNT:
    value: ""
    description: The "Child" account locator, that was created inside the Org account.

  # NEW for DataOps.live Events
  DATAOPS_SNOWFLAKE_USER:
    value: ""
    description: The service user username for the "Child" account (not the Org service account).

  # NEW for DataOps.live Events
  DATAOPS_SNOWFLAKE_AUTH: "KEY_PAIR"
  DATAOPS_SNOWFLAKE_KEY_PAIR:
    value: ""
    description: The service user PRIVATE KEY for the "Child" account (not the Org service account).

  ## This sets all compatible jobs into DEBUG mode.
  ## NOTE: THIS WILL EXPOSE PASSWORDS IN LOGS - IF YOU USE THIS BE SURE TO DELETE YOUR PIPELINES IMMEDIATELY AFTER DEBUGGING IS COMPLETE
  ## Usually you would set this as a pipeline variable for a single pipeline run rather than in a -ci.yml file
  ## See https://docs.dataops.live/docs/concepts/project-settings/
  DATAOPS_DEBUG:
    value: ""
    options: ["", "1"]
    description: Enable debug output in jobs
